[versions]
annotationJvm = "1.9.1"
appcompat = "1.6.1"

[libraries]
androidx-annotation-jvm = { module = "androidx.annotation:annotation", version.ref = "annotationJvm" }  # Changed from "annotation" to "annotationJvm"
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }